#!/bin/bash
#SBATCH -J test_file                         # Job name
#SBATCH -o robot_arm/logs/test_file_%j.out                  # output file (%j expands to jobID)
#SBATCH -e robot_arm/logs/test_file_%j.err                  # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                      # Request status by email 
#SBATCH --mail-user=tty6@cornell.edu        # Email address to send results to.
#SBATCH -N 1                                 # Total number of nodes requested
#SBATCH -n 32                                 # Total number of cores requested
#SBATCH --get-user-env                       # retrieve the users login environment
#SBATCH --mem=32g                           # server memory requested (per node)
#SBATCH -t 72:00:00                           # Time limit (hh:mm:ss)
#SBATCH --partition=gpu                     # Request partition
#SBATCH --gres=gpu:1                        # Request gpu
. /home/tty6/miniforge3/etc/profile.d/conda.sh
eval "$(conda shell.bash hook)"
cd /home/tty6/MyoSuite-Assistive
conda activate myosuite
export PYTHONPATH=/home/tty6/MyoSuite-Assistive:$PYTHONPATH
find /dev/shm -maxdepth 1 -user "$USER" -type f -print -delete || true
ipcs -s | awk -v u="$USER" '$3==u {print $2}' | xargs -r -n1 ipcrm -s
python -m deprl.main "$@"