#!/bin/bash
#SBATCH -J test_file                         # Job name
#SBATCH -o robot_arm/logs/%j/test_file_%j.out                  # output file (%j expands to jobID)
#SBATCH -e robot_arm/logs/%j/test_file_%j.err                  # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                      # Request status by email 
#SBATCH --mail-user=tty6@cornell.edu        # Email address to send results to.
#SBATCH -N 1                                 # Total number of nodes requested
#SBATCH -n 16                                 # Total number of cores requested
#SBATCH --get-user-env                       # retrieve the users login environment
#SBATCH --mem=32g                           # server memory requested (per node)
#SBATCH -t 24:00:00                           # Time limit (hh:mm:ss)
#SBATCH --partition=gpu                     # Request partition
#SBATCH --gres=gpu:1                        # Request gpu
/home/tty6/MyoSuite-Assistive/robot_arm/scripts/test-job.sh 